### ISSUE TITLE
Version 2.2.2

### ISSUE THREAD

**Issue by sbloedel** [ethanselzer/react-image-magnify#16] opened 2017-11-16 20:15 UTC
Should be fixed as part of PR
https://github.com/ethanselzer/react-image-magnify/pull/17

Getting this error when using version 2.2.2.  We did not have this issue in v2.2.1 so we rolled back to v2.2.1.  Not sure what this issue could be.  Thought I'd enter an issue for now.

After further research, it appears as if the following line in ReactImageMagnify.js may fix it:
var _lens = require('../src/lib/lens'); 
to
var _lens = require('./lib/lens'); 

Here's part of a call stack.
module.js:471
throw err;
^

Error: Cannot find module '../src/lib/lens'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/x/x/x/x/x/node_modules/react-image-magnify/dist/ReactImageMagnify.js:41:13)

**Comment by ethanselzer** [comment] 2017-11-17 15:23
@sbloedel - Thanks very much for identifying this issue and correcting it! I apologize for the broken build. Please try the latest release, v2.2.3, and confirm the issue is resolved.

**Comment by ethanselzer** [comment] 2017-11-20 04:10
Fixed by #17

**Comment by ethanselzer** [comment] 2017-11-22 14:57
@sbloedel - Thanks again for identifying this issue and for providing the fix. If you find react-image-magnify useful, please consider starring it on GitHub. Starring helps to grow the project, which benefits everyone.

**Closed by ethanselzer** 2017-11-22 14:57 UTC
